eventbrite_like/config/routes.rb
Rails.application.routes.draw do
  get 'admin/check_if_admin'
  root 'events#index'

  devise_for :users, :controllers => {
    registrations: 'registrations'}

  resources :users, only: [:show] do
    resources :avatars, only: [:create]
  end

  resources :events do
    resources :attendances, only: [:index, :new, :create]
    resources :event_pictures
  end
  
  namespace :admin do
    root 'admin#show'
    resources :events, :users, :event_submissions
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

eventbrite_like/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :event_admins, foreign_key: 'event_admin_id', class_name: 'Event', dependent: :destroy
  has_many :events
  has_many :events, through: :attendances
  has_many :attendances

  after_create :welcome_send

  has_one_attached :avatar
  
  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end
  
end

eventbrite_like/app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :check_if_admin
  
  def index
    @users = User.all
  end

  def destroy
    @user = User.find(params[:id])

    if @user.destroy
    flash[:success] = "Utilisateur supprimé"
    redirect_to admin_users_path
    else
      flash[:failure] = "L'utilisateur n'a pas pu être supprimé"
      redirect_to admin_users_path
    end
  end

    def update
      @user = User.find(params[:id])
      if @user.update(user_params)
        flash[:success] = "Utilisateur modifié!"
        redirect_to admin_users_path
      else
        render :edit
      end
    end

    def edit
      @user = User.find(params[:id])
    end

    private

    def user_params
      params.require(:user).permit(:first_name, :last_name, :description, :email, :is_admin)
    end

  
end

eventbrite_like/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, :right_user

  def show
    @user = User.find(params[:id])
    @event_admin = Event.all
  end

private

  def right_user
    @user = User.find(params[:id])
    if current_user.id == @user.id
    else
      redirect_to root_path
  end
end
end

eventbrite_like/app/helpers/users_helper.rb
module UsersHelper
end

eventbrite_like/app/views/admin/users/index.html.erb
<!doctype html>
<html lang="fr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="/docs/4.0/assets/img/favicons/favicon.ico">

    <title>Dashboard Template for Bootstrap</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/dashboard/">

    <!-- Bootstrap core CSS -->
    <link href="../../dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="dashboard.css" rel="stylesheet">
  </head>

  <body>
    <div class="container-fluid">
      <div class="row">
        <nav class="col-md-2 mt-5 d-none d-md-block bg-light sidebar">
          <div class="sidebar-sticky">
            <ul class="nav flex-column">
              <li class="nav-item">
                <a class="nav-link active" href="<%= admin_root_path %>">
                  <span data-feather="home"></span>
                  Dashboard <span class="sr-only">(current)</span>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="<%= admin_events_path %>">
                  <span data-feather="calendar"></span>
                  Évènements
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="<%= admin_users_path %>">
                  <span data-feather="users"></span>
                  Utilisateurs
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="<%= admin_event_submissions_path %>">
                  <span data-feather="check-circle"></span>
                  Vérifications
                </a>
            </ul>

          </div>
        </nav>

        <main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
          <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
            <h1 class="h2">Dashboard</h1>
            <div class="btn-toolbar mb-2 mb-md-0">
              <div class="btn-group mr-2">
                <button class="btn btn-sm btn-outline-secondary">Share</button>
                <button class="btn btn-sm btn-outline-secondary">Export</button>
              </div>
              <button class="btn btn-sm btn-outline-secondary dropdown-toggle">
                <span data-feather="calendar"></span>
                This week
              </button>
            </div>
          </div>

          <h2>Gestion utilisateurs</h2>
          
          <div class="table-responsive">
            <table class="table table-striped table-sm">
              <thead>
                <tr>
                  <th>Prénom</th>
                  <th>Nom</th>
                  <th>Email</th>
                  <th>Supprimer</th>
                  <th>Admin</th>
                </tr>
              </thead>
              <tbody>
              <%  @users.each do |user| %>
                <tr>
                  <td><%=user.first_name%></td>
                  <td><%=user.last_name%></td>
                  <td><%=user.email%></td>
                  <td><a href="<%= admin_user_path(user.id)%>" data-confirm="Voulez-vous vraiment supprimer cet utilisateur ?" data-method="DELETE"><i class="fas fa-trash ml-4"></i></a></td>
                  <td><%= form_for user, url:admin_user_path(user.id),method: :patch do |f| %>
                  <div class="field ml-3">
                   <%= f.check_box :is_admin %>
                   <%= f.submit "Actualiser", class: "btn btn-outline-primary align-middle btn-sm p-1 " %>
                  </div> <% end %> </td>
                  

                </tr>
                <%end%>
              </tbody>
            </table>
          </div>
          
        </main>
      </div>
    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
    <script src="../../assets/js/vendor/popper.min.js"></script>
    <script src="../../dist/js/bootstrap.min.js"></script>

    <!-- Icons -->
    <script src="https://unpkg.com/feather-icons/dist/feather.min.js"></script>
    <script>
      feather.replace()
    </script>

    <!-- Graphs -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.1/Chart.min.js"></script>
    <script>
      var ctx = document.getElementById("myChart");
      var myChart = new Chart(ctx, {
        type: 'line',
        data: {
          labels: ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"],
          datasets: [{
            data: [15339, 21345, 18483, 24003, 23489, 24092, 12034],
            lineTension: 0,
            backgroundColor: 'transparent',
            borderColor: '#007bff',
            borderWidth: 4,
            pointBackgroundColor: '#007bff'
          }]
        },
        options: {
          scales: {
            yAxes: [{
              ticks: {
                beginAtZero: false
              }
            }]
          },
          legend: {
            display: false,
          }
        }
      });
    </script>
  </body>
</html>