the_gossip_project/config/routes.rb
Rails.application.routes.draw do


  root 'gossips#index'

  get '/contact', to: 'static#contact'

  get '/team', to: 'static#team'

  get '/login'     => 'sessions#new'

  post '/login'    => 'sessions#create'

  delete '/logout' => 'sessions#destroy'  
  
  resources :gossips
  resources :users
  resources :cities, only:[:show]
  resources :comments
  resources :sessions, only: [:new, :create, :destroy]
  
end

the_gossip_project/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

the_gossip_project/app/models/city.rb
class City < ApplicationRecord
  has_many :users
end

the_gossip_project/app/models/comment.rb
class Comment < ApplicationRecord
end

the_gossip_project/app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :user
  has_many :JoinTableTagGossips
  has_many :tags, through: :JoinTableTagGossips

  validates :title, presence: true, 
  length: { minimum: 3, maximum: 20, message: "Le titre doit contenir entre 3 et 14 caractères."} 
  validates :content,presence: true
end

the_gossip_project/app/models/join_table_tag_gossip.rb
class JoinTableTagGossip < ApplicationRecord
  belongs_to :gossip
  belongs_to :tag
end

the_gossip_project/app/models/like.rb
class Like < ApplicationRecord
end

the_gossip_project/app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  has_many :LierPrivateMessageUsers
  has_many :receivers,through: :LierPrivateMessageUsers,source: :user
  belongs_to :sender, class_name: "User"
  

end

the_gossip_project/app/models/tag.rb
class Tag < ApplicationRecord
  has_many :JoinTableTagGossips
  has_many :gossips, through: :JoinTableTagGossips
end

the_gossip_project/app/models/user.rb
class User < ApplicationRecord
  belongs_to :city

  has_many :LierPrivateMessageUsers
  has_many :received_messages,through: :LierPrivateMessageUsers, source: :private_message
  has_many :sent_messages, foreign_key: 'sender_id',class_name: "PrivateMessage"
  
  has_secure_password
  validates :first_name, :last_name, :description, :email, :age, presence:true
  validates :age, :numericality=> true, :inclusion => {:in => 1..80, :message => "Value should be between 0 and 4"}
  validates :first_name, :last_name, length: {in: 2..30}
  validates :description, length: {in: 3..1000}
  validates :email, uniqueness:true, format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "email adress please"}
end

the_gossip_project/app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def show
    @city = City.find(params[:id])
    @users = User.where(city_id: params[:id])
    @gossips = Gossip.where(user_id: @users)
  end
end

the_gossip_project/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
    @cities = City.all
  end

  def create
    
=begin
    @user = User.new(
      email: params[:email],
      password: params[:password],
      password_confirmation: params[:password_confirmation],
      city_id: 19,
      description: params[:description],
      age: params[:age],
      first_name: params[:first_name],
      last_name: params[:last_name]
    )
=end

    @user = User.new(params.permit(:first_name, :last_name, :email, :age, :description, :password,))
    @user.city = City.find_by(params.permit(:zip_code))
    @user.valid?

    if @user.save
      flash[:success] = "Compte bien créé !"
      redirect_to root_path
    else
      flash[:failure] = "Erreur lors de la création du compte !"
      render 'new'
    end
  end
end

the_gossip_project/app/helpers/application_helper.rb
module ApplicationHelper
end

the_gossip_project/app/helpers/cities_helper.rb
module CitiesHelper
end

the_gossip_project/app/helpers/comments_helper.rb
module CommentsHelper
end

the_gossip_project/app/helpers/gossips_helper.rb
module GossipsHelper
end

the_gossip_project/app/helpers/home_helper.rb
module HomeHelper
end

the_gossip_project/app/helpers/sessions_helper.rb
module SessionsHelper
  
  def current_user
    User.find_by(id: session[:user_id])
  end

  def log_in(user)
    session[:user_id] = user.id
  end

end

the_gossip_project/app/helpers/static_helper.rb
module StaticHelper
end

the_gossip_project/app/helpers/user_helper.rb
module UserHelper
end

the_gossip_project/app/helpers/welcome_helper.rb
module WelcomeHelper
end

the_gossip_project/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheGossipProject</title>
   <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.2/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>

      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand text-warning " <%= link_to "The Gossip Project", root_path %></a>
        <button
          class="navbar-toggler"
          type="button"
          data-toggle="collapse"
          data-target="#navbarTogglerDemo02"
          aria-controls="navbarTogglerDemo02"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
  
        <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
          <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
            <li class="nav-item active">
              <a class="nav-link"<%= link_to "Accueil", root_path %></a>
                <span class="sr-only"></span>
            </li>
            <li class="nav-item">
              <a class="nav-link"<%= link_to "Créer un gossip", new_gossip_path %></a>
              </li>


          <li class="nav-item dropdown">
              <a
                class="nav-link dropdown-toggle"
                href="#"
                id="navbarDropdown"
                role="button"
                data-toggle="dropdown"
                aria-haspopup="true"
                aria-expanded="false"
              >
                Compte
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <% if current_user %>
                <a class="dropdown-item"<%= link_to "Se déconnecter", session_path(session.id), method: :delete %></a>
                <%else%>
                <a class="dropdown-item"<%= link_to "Créer un compte", new_user_path %></a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item"<%= link_to "Se connecter", new_session_path %></a>
                
                <%end%>
              </div>
            </li>


            

            <li class="nav-item dropdown">
              <a
                class="nav-link dropdown-toggle"
                href="#"
                id="navbarDropdown"
                role="button"
                data-toggle="dropdown"
                aria-haspopup="true"
                aria-expanded="false"
              >
                Autre
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item"<%= link_to "Contact", contact_path %></a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item"<%= link_to "Présentation de l'équipe", team_path %></a>
              </div>
            </li>
          </ul>
        </div>
      </nav>


    <% if flash[:success] %>
    <div class="alert alert-success"> <%=flash[:success]%></div>
    <% end%>
    <% if flash[:failure] %>
    <div class="alert alert-danger alert-dismissible fade show" role="alert"> <%=flash[:failure]%></div>
    <% end %>
    
    
    </div>
    <%= yield %>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.1/umd/popper.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.2/js/bootstrap.min.js"></script>
  </body>
</html>