eventbrite_like/config/routes.rb
Rails.application.routes.draw do
  get 'admin/check_if_admin'
  root 'events#index'

  devise_for :users, :controllers => {
    registrations: 'registrations'}

  resources :users, only: [:show] do
    resources :avatars, only: [:create]
  end

  resources :events do
    resources :attendances, only: [:index, :new, :create]
    resources :event_pictures
  end
  
  namespace :admin do
    root 'admin#show'
    resources :events, :users, :event_submissions
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

eventbrite_like/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

eventbrite_like/app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :user
  belongs_to :event

  after_create :join_event

  def join_event
    AttendanceMailer.join_event(self).deliver_now
  end
end

eventbrite_like/app/models/event.rb
class Event < ApplicationRecord
  
  has_many :attendances
  has_many :users, through: :attendances
  belongs_to :user, optional: true
  belongs_to :event_admin, class_name: 'User', optional: true
  
  validates :start_date, presence: true
  validate :is_future?

  validates :duration, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validate :divisable_by_five? 

  validates :title, presence: true, length: { in: 3..140}

  validates :description, presence: true, length: { in: 5..240}

  validates :price, presence: true, numericality: {only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 1000}

  validates :location, presence: true
  private

  has_one_attached :event_picture

  def is_future?
    if start_date != nil
      if Time.now > start_date
        errors.add(:start_date, "date de départ peut pas être passée !")
      end
    end
    end

  def divisable_by_five?
    if duration != nil
      if duration % 5 != 0
        errors.add(:duration, "durée doit être multiple de 5")
      end
    end
    end

end

eventbrite_like/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :event_admins, foreign_key: 'event_admin_id', class_name: 'Event', dependent: :destroy
  has_many :events
  has_many :events, through: :attendances
  has_many :attendances

  after_create :welcome_send

  has_one_attached :avatar
  
  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end
  
end

eventbrite_like/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  require 'resolv-replace'

  protect_from_forgery with: :exception
  before_action :authenticate_user!

  
  def check_if_admin
    unless current_user.is_admin?
      redirect_to root_path 
    end
  end
  
end

eventbrite_like/app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  def new
    @event = Event.find(params[:event_id])
  end
  
  def create
    
    @event = Event.find(params[:event_id])
    @amount = @event.price * 100

    customer = Stripe::Customer.create({
      email: params[:stripeEmail],
      source: params[:stripeToken],
    })
  
    charge = Stripe::Charge.create({
      customer: customer.id,
      amount: @amount,
      description: 'Inscription',
      currency: 'EUR',
    })

    attendance_params = params.permit[:event_id]
    @attendance = Attendance.create(user_id: current_user.id, event_id: @event.id, strip_customer_id: customer.id)

    redirect_to event_path(@event.id)


  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_event_attendance_path

  end

end

eventbrite_like/app/controllers/avatars_controller.rb
class AvatarsController < ApplicationController

  def create
  @user = User.find(params[:user_id])
  @user.avatar.attach(params[:avatar])
  redirect_to(user_path(@user))
  end

end

eventbrite_like/app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def new
    @event = Event.find(params[:event_id])
  end
  
  def create
    
    @event = Event.find(params[:event_id])
    @amount = @event.price * 100

    customer = Stripe::Customer.create({
      email: params[:stripeEmail],
      source: params[:stripeToken],
    })
  
    charge = Stripe::Charge.create({
      customer: customer.id,
      amount: @amount,
      description: 'Inscription',
      currency: 'EUR',
    })
  

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_event_attendance_path

  end


end

eventbrite_like/app/controllers/event_pictures_controller.rb
class EventPicturesController < ApplicationController
  def create
  @event = Event.find(params[:event_id])
  @event.event_picture.attach(params[:event_picture])
  redirect_to(event_path(@event))
  end

  
end

eventbrite_like/app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]

  def index
    @event = Event.where(validated: true)
  end

  def new
    @event = Event.new
  end

  def show
    @event = Event.find(params[:id])
  end

  def create
    @event = Event.new(params_event)
    @event.event_admin_id = current_user.id

    if @event.save
      redirect_to event_path(@event.id)
    else render 'new'
    end
  end

  private

  def params_event
    params.require(:event).permit(:start_date, :duration, :title, :description, :price, :location, :event_picture)
  end
end

eventbrite_like/app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

    def sign_up_params
      params.require(:user).permit(:email, :password, :first_name, :last_name, :description)
    end
end

eventbrite_like/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, :right_user

  def show
    @user = User.find(params[:id])
    @event_admin = Event.all
  end

private

  def right_user
    @user = User.find(params[:id])
    if current_user.id == @user.id
    else
      redirect_to root_path
  end
end
end

eventbrite_like/app/helpers/admin_helper.rb
module AdminHelper
end

eventbrite_like/app/helpers/application_helper.rb
module ApplicationHelper
end

eventbrite_like/app/helpers/attendances_helper.rb
module AttendancesHelper
end

eventbrite_like/app/helpers/avatars_helper.rb
module AvatarsHelper
end

eventbrite_like/app/helpers/charges_helper.rb
module ChargesHelper
end

eventbrite_like/app/helpers/event_pictures_helper.rb
module EventPicturesHelper
end

eventbrite_like/app/helpers/events_helper.rb
module EventsHelper
end

eventbrite_like/app/helpers/users_helper.rb
module UsersHelper
end

eventbrite_like/app/views/admin/admin/show.html.erb
<!doctype html>
<html lang="fr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="/docs/4.0/assets/img/favicons/favicon.ico">

    <title>Dashboard Template for Bootstrap</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/dashboard/">

    <!-- Bootstrap core CSS -->
    <link href="../../dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="dashboard.css" rel="stylesheet">
  </head>

  <body>
    <div class="container-fluid">
      <div class="row">
        <nav class="col-md-2 mt-5 d-none d-md-block bg-light sidebar">
          <div class="sidebar-sticky">
            <ul class="nav flex-column">
              <li class="nav-item">
                <a class="nav-link active" href="#">
                  <span data-feather="home"></span>
                  Dashboard <span class="sr-only">(current)</span>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="<%= admin_events_path %>">
                  <span data-feather="calendar"></span>
                  Évènements
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="<%= admin_users_path %>">
                  <span data-feather="users"></span>
                  Utilisateurs
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="<%= admin_event_submissions_path %>">
                  <span data-feather="check-circle"></span>
                  Vérifications
                </a>
            </ul>

          </div>
        </nav>

        <main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
          <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
            <h1 class="h2">Dashboard</h1>
            <div class="btn-toolbar mb-2 mb-md-0">
              <div class="btn-group mr-2">
                <button class="btn btn-sm btn-outline-secondary">Share</button>
                <button class="btn btn-sm btn-outline-secondary">Export</button>
              </div>
              <button class="btn btn-sm btn-outline-secondary dropdown-toggle">
                <span data-feather="calendar"></span>
                This week
              </button>
            </div>
          </div>

          <canvas class="my-4" id="myChart" width="800" height="300"></canvas>

          <h2>Évènements à venir</h2>
          
          <div class="table-responsive">
            <table class="table table-striped table-sm">
              <thead>
                <tr>
                  <th>#</th>
                  <th>Titre</th>
                  <th>Prix</th>
                  <th>Créateur</th>
                  <th>Date</th>
                </tr>
              </thead>
              <tbody>
              <% @events.sort_by(&:start_date).each do |event| %>
                <tr>
                  <td><%=event.id%></td>
                  <td><%=event.title%></td>
                  <td><%=event.price%> €</td>
                  <td><%=event.event_admin.email%></td>
                  <td><%=event.start_date.strftime('%d %B, %Y - %HH%M')%></td>

                </tr>
                <%end%>
              </tbody>
            </table>
          </div>
          
        </main>
      </div>
    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
    <script src="../../assets/js/vendor/popper.min.js"></script>
    <script src="../../dist/js/bootstrap.min.js"></script>

    <!-- Icons -->
    <script src="https://unpkg.com/feather-icons/dist/feather.min.js"></script>
    <script>
      feather.replace()
    </script>

    <!-- Graphs -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.1/Chart.min.js"></script>
    <script>
      var ctx = document.getElementById("myChart");
      var myChart = new Chart(ctx, {
        type: 'line',
        data: {
          labels: ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"],
          datasets: [{
            data: [15339, 21345, 18483, 24003, 23489, 24092, 12034],
            lineTension: 0,
            backgroundColor: 'transparent',
            borderColor: '#007bff',
            borderWidth: 4,
            pointBackgroundColor: '#007bff'
          }]
        },
        options: {
          scales: {
            yAxes: [{
              ticks: {
                beginAtZero: false
              }
            }]
          },
          legend: {
            display: false,
          }
        }
      });
    </script>
  </body>
</html>